# Generated by Django 4.1.3 on 2022-12-21 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=35)),
                ("file_name", models.CharField(max_length=100)),
                ("current_row", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UpdatedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_file",
                        to="leads_data.datafile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        related_name="manager_of_spaces", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_of_space",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "writers",
                    models.ManyToManyField(
                        related_name="writer_of_spaces", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datafile",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="leads_data.documentspace",
            ),
        ),
    ]
