# Generated by Django 4.1.6 on 2023-02-18 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managers', models.ManyToManyField(related_name='manager_of_spaces', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_space', to=settings.AUTH_USER_MODEL)),
                ('writers', models.ManyToManyField(related_name='writer_of_spaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100, unique=True)),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('current_row', models.IntegerField(default=0)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='leads_data.documentspace')),
                ('web_content_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100, unique=True)),
                ('data_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_file', to='leads_data.datafile')),
                ('web_content_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=14)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approached_individuals', to='leads_data.datafile')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='leads_data.individual')),
            ],
        ),
        migrations.AddIndex(
            model_name='individual',
            index=models.Index(fields=['data_file', 'row_no'], name='leads_data__data_fi_614cc1_idx'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ArchivedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=14)),
                ('responses', models.JSONField()),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_responses', to='leads_data.datafile')),
            ],
        ),
        migrations.RenameModel(
            old_name='Individual',
            new_name='Student',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='leads_data__data_fi_83c1bd_idx',
            old_name='leads_data__data_fi_614cc1_idx',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='leads_data.student')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(default='Empty', max_length=200),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='archivedresponse',
            old_name='responses',
            new_name='data',
        ),
        migrations.AddField(
            model_name='student',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('started', 'Interaction Started'), ('not_interested', 'Not Interested'), ('interested', 'Interested'), ('denied', 'Denied Admission'), ('confirmed', 'Admission Confirmed')], default='started', max_length=14),
        ),
        migrations.DeleteModel(
            name='ArchivedResponse',
        ),
        migrations.AlterField(
            model_name='datafile',
            name='current_row',
            field=models.IntegerField(default=1),
        ),
    ]
