# Generated by Django 4.1.3 on 2023-01-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="datafile",
            name="file_id",
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name="datafile",
            name="file_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="UpdatedFile",
        ),
        migrations.AddField(
            model_name="responsefile",
            name="data_file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_file",
                to="leads_data.datafile",
            ),
        ),
    ]
