# Generated by Django 4.1.6 on 2023-03-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='First Last', max_length=50),
            preserve_default=False,
        ),
    ]
