# Generated by Django 4.1.3 on 2023-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads_data", "0002_responsefile_alter_datafile_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafile",
            name="webContentLink",
            field=models.URLField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="responsefile",
            name="webContentLink",
            field=models.URLField(),
            preserve_default=False,
        ),
    ]
