# Generated by Django 4.1.3 on 2023-01-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads_data", "0003_datafile_webcontentlink_responsefile_webcontentlink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datafile",
            old_name="webContentLink",
            new_name="web_content_link",
        ),
        migrations.RenameField(
            model_name="responsefile",
            old_name="webContentLink",
            new_name="web_content_link",
        ),
    ]
