# Generated by Django 4.1.3 on 2023-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads_data", "0004_rename_webcontentlink_datafile_web_content_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafile",
            name="file_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="responsefile",
            name="file_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
