# Generated by Django 4.1.3 on 2022-12-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_rename_googlecredentials_googlecredential_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portaluser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
