# Generated by Django 4.1.3 on 2022-12-06 17:53

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_portaluser_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GoogleCredentials",
            new_name="GoogleCredential",
        ),
        migrations.AlterField(
            model_name="portaluser",
            name="password",
            field=models.CharField(
                default=authentication.models.get_random_string_60,
                max_length=128,
                verbose_name="password",
            ),
        ),
    ]
