# Generated by Django 4.1.3 on 2022-12-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_portaluser_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoogleCredential",
        ),
    ]
