# Generated by Django 4.1.3 on 2022-12-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_delete_googlecredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="portaluser",
            name="is_space_owner",
            field=models.BooleanField(default=False, verbose_name="Is Space Owner"),
        ),
    ]
