# Generated by Django 4.1.3 on 2023-01-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_portaluser_is_space_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portaluser",
            name="is_space_owner",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user will have their own space or not",
                verbose_name="Is Space Owner",
            ),
        ),
    ]
