AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Parameters:
  ProjectName:
    Description: The name of the project
    Type: String
Resources:
  MyInstance:
    Properties:
      DBName: !Sub "leads_management_database"
      MasterUsername: "postgres"
      DBInstanceClass: "db.t3.micro"
      Engine: "postgres"
      EngineVersion: "15.2"
      # noinspection YAMLSchemaValidation
      AllocatedStorage: 20
      AutoMinorVersionUpgrade: true
      ManageMasterUserPassword: true
      
      MasterUserSecret:
        KmsKeyId: !Ref KMSKey
    Type: "AWS::RDS::DBInstance"

  KMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: Manual test KMS key
      EnableKeyRotation: True
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Ref "AWS::StackName"
        Statement:
          - Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS:
                Fn::Sub: 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action:
              - "kms:*"
            Resource: "*"

Outputs:
  Secret:
    Value:
      Fn::GetAtt: MyInstance.MasterUserSecret.SecretArn
