AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ProjectName:
    Description: The name of the project
    Type: String
Resources:
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub 'https://techoon-global-config.s3.ap-south-1.amazonaws.com/deployments/${ProjectName}/cf/vpc.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
#  DatabaseStack:
#    Type: 'AWS::CloudFormation::Stack'
#    Properties:
#      TemplateURL: !Sub 'https://techoon-global-config.s3.ap-south-1.amazonaws.com/deployments/${ProjectName}/cf/db.yaml'
#      Parameters:
#        ProjectName: !Ref ProjectName