Metadata:
  'AWS::CloudFormation::Designer':
    09bf8694-15e6-4286-8aa3-bf2561de3ca9:
      size:
        width: 60
        height: 60
      position:
        x: 71.19199564729192
        'y': 101.85458146604351
      z: 0
Resources:
  DatabaseStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties: {}