AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ProjectName:
    Description: The name of the project
    Type: String
  ProjectDeploymentsS3Url:
    Description: The S3 under which the s3 files are uploaded
    Type: String
  ECRImage:
    Description: The ECR Docker Image URL
    Type: String
  DbKmsKeyId:
    Description: The KMS Key to use for RDS Instance credentials secret 
    Type: String
Resources:
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub '${ProjectDeploymentsS3Url}/cf/vpc.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
    UpdateReplacePolicy:  Delete
    DeletionPolicy: Delete
  DatabaseStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub '${ProjectDeploymentsS3Url}/cf/db.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        PublicSecurityGroup: !GetAtt VPCStack.Outputs.PublicSecurityGroup
        KmsKeyId: !Ref DbKmsKeyId
    UpdateReplacePolicy:  Delete
    DeletionPolicy: Delete
  EcsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${ProjectDeploymentsS3Url}/cf/ecs.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        DBInstanceHost: !GetAtt DatabaseStack.Outputs.DBInstanceHost
        DBInstancePort: !GetAtt DatabaseStack.Outputs.DBInstancePort
        DBName: !GetAtt DatabaseStack.Outputs.DBName
        DBSecretArn: !GetAtt DatabaseStack.Outputs.DBSecretArn
        DBSecretKmsArn: !GetAtt DatabaseStack.Outputs.DBSecretKmsArn
        ECRImage: !Ref ECRImage
        PublicSecurityGroup: !GetAtt VPCStack.Outputs.PublicSecurityGroup
        SubnetIds: !Join
          - ","
          - - !GetAtt VPCStack.Outputs.PublicSubnet1
            - !GetAtt VPCStack.Outputs.PublicSubnet2
    UpdateReplacePolicy:  Delete
    DeletionPolicy: Delete

